version: "2.4"
services:
    recorder:
        build: .
        volumes:
            - .:/var/motion/
        ports:
            - "8080:8080"
            - "8081:8081"
        devices: 
            - "/dev/video4:/dev/video0"
        command: motion -n -c /var/motion/motion.conf
        restart: unless-stopped

    browser:
        image: filebrowser/filebrowser
        volumes: 
            - ./recordings:/srv:rw
        ports:
            - "5050:80"
        restart: unless-stopped
